### ISSUE TITLE
Invalid JWT

### ISSUE THREAD

**Issue by briangruber** [erjohnso/logstash-input-google_pubsub#1]
Thanks for creating this input plugin. I simply can't get it to authorize on my local machine using what seems like a correct credential.json file from Google. I keep getting an `Invalid JWT` error that appears to come from `@client.authorization.fetch_access_token!`

`Error: Authorization failed.  Server message:\n{\n  \"error\" : \"invalid_grant\",\n  \"error_description\" : \"Invalid JWT: Token must be a short-lived token and in a reasonable timeframe\"\n}", :level=>:error}`

Any ideas?

**Comment by erjohnso** [comment]
Woah! Sorry @briangruber, I completely missed this and I hope you managed to get it working!

As an FYI, I'm deleting this repo to create a fork of upstream to get this plugin accepted. If you're still having issues, then we'll need to create a new issue there and then get it fixed up.
